[package]
name = "sample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.12.0"
rand_core = "0.6"


[features]
default = ["superbanana"]
superbanana = []

[workspace]
